import { create } from "zustand";

export type MeetingStatus = "scheduled" | "live" | "ended";

export interface MeetingRecording {
  id: string;
  title: string;
  url: string;
  durationMins: number;
  recordedAt: string;
  sizeMb: number;
  views?: number;
}

export interface MeetingAttendee {
  id: string;
  name: string;
  email: string;
  role: "moderator" | "viewer";
  joinedAt?: string;
  leftAt?: string;
  // ── Analytics (per-attendee) ──
  talkTimeSec?: number;
  chatMsgs?: number;
  pollsAnswered?: number;
  attentivenessPct?: number; // 0-100 (focus / window in foreground)
  handRaiseCount?: number;
  cameraOnPct?: number;
}

export interface MeetingPoll {
  id: string;
  question: string;
  options: string[];
  responseCount: number;
  correctIdx?: number;
  correctPct?: number;
  askedAtSec?: number; // session-relative
}

/** BBB-aligned config — what the edge function will send to /create */
export interface BBBConfig {
  meetingID: string;
  attendeePW: string;
  moderatorPW: string;
  record: boolean;
  autoStartRecording: boolean;
  allowStartStopRecording: boolean;
  muteOnStart: boolean;
  allowModsToUnmuteUsers: boolean;
  webcamsOnlyForModerator: boolean;
  guestPolicy: "ALWAYS_ACCEPT" | "ASK_MODERATOR" | "ALWAYS_DENY";
  lockSettingsDisableCam: boolean;
  lockSettingsDisableMic: boolean;
  lockSettingsDisablePrivateChat: boolean;
  lockSettingsDisablePublicChat: boolean;
  lockSettingsDisableNote: boolean;
  layout?: "CUSTOM_LAYOUT" | "PRESENTATION_FOCUS" | "VIDEO_FOCUS";
  breakoutRoomsEnabled?: boolean;
  meta?: Record<string, string>;
}

/** Engagement / attendance roll-up generated by callbacks + analytics */
export interface MeetingAnalytics {
  engagementScore: number; // 0-100
  attendanceRate: number;  // 0-100 (% of invited that joined)
  peakAttendees: number;
  avgTalkTimeSec: number;
  chatMsgCount: number;
  pollsCount: number;
  handRaisesCount: number;
  recordingViews: number;
  avgAttentivenessPct: number;
  /** Minute-by-minute time series */
  timeline: { t: number; attendees: number; engagement: number }[];
  polls: MeetingPoll[];
}

export interface Meeting {
  id: string;
  title: string;
  description?: string;
  batchId?: string;
  batchName?: string;
  trainerId?: string;
  trainerName?: string;
  scheduledAt: string; // ISO
  durationMins: number;
  status: MeetingStatus;
  joinUrl: string;
  moderatorJoinUrl?: string;
  welcome?: string;
  // Legacy convenience mirrors of bbb.* — kept for backward compat
  record: boolean;
  muteOnJoin: boolean;
  waitingRoom: boolean;
  maxAttendees: number;
  invitedCount?: number;
  attendees: MeetingAttendee[];
  recordings: MeetingRecording[];
  bbb?: BBBConfig;
  analytics?: MeetingAnalytics;
}

const now = new Date();
const offset = (days: number, hours = 0) => {
  const d = new Date(now);
  d.setDate(d.getDate() + days);
  d.setHours(10 + hours, 0, 0, 0);
  return d.toISOString();
};

const genTimeline = (mins: number, base: number, peak: number) =>
  Array.from({ length: mins }, (_, t) => {
    const ramp = Math.min(1, t / 10);
    const fall = Math.max(0, 1 - Math.max(0, t - (mins - 10)) / 10);
    const attendees = Math.round(base + (peak - base) * ramp * fall + Math.sin(t / 4) * 1.5);
    const engagement = Math.max(30, Math.min(100, 70 + Math.sin(t / 3) * 12 + (t / mins) * 6));
    return { t, attendees, engagement: Math.round(engagement) };
  });

const seedBBB = (id: string, record: boolean): BBBConfig => ({
  meetingID: `bbb-${id}`,
  attendeePW: "ap-xxxxxx",
  moderatorPW: "mp-xxxxxx",
  record,
  autoStartRecording: false,
  allowStartStopRecording: true,
  muteOnStart: true,
  allowModsToUnmuteUsers: true,
  webcamsOnlyForModerator: false,
  guestPolicy: "ALWAYS_ACCEPT",
  lockSettingsDisableCam: false,
  lockSettingsDisableMic: false,
  lockSettingsDisablePrivateChat: false,
  lockSettingsDisablePublicChat: false,
  lockSettingsDisableNote: false,
  layout: "CUSTOM_LAYOUT",
  breakoutRoomsEnabled: false,
  meta: { source: "cloudadda", env: "dev" },
});

const initial: Meeting[] = [
  {
    id: "m-1",
    title: "Java Fundamentals — Day 14 Live Session",
    description: "Collections deep dive with live coding.",
    batchId: "10", batchName: "Java Fundamentals — Cohort 24",
    trainerId: "t-1", trainerName: "Rahul Verma",
    scheduledAt: new Date().toISOString(),
    durationMins: 90,
    status: "live",
    joinUrl: "#bbb-join-pending",
    moderatorJoinUrl: "#bbb-mod-pending",
    welcome: "Welcome! Today: Collections deep dive.",
    record: true, muteOnJoin: true, waitingRoom: false,
    maxAttendees: 50,
    invitedCount: 42,
    attendees: [
      { id: "a1", name: "Rahul Verma", email: "rahul@cloudadda.com", role: "moderator", joinedAt: "10:00", talkTimeSec: 1820, chatMsgs: 4, pollsAnswered: 0, attentivenessPct: 100, handRaiseCount: 0, cameraOnPct: 95 },
      { id: "a2", name: "Alice K.", email: "alice@example.com", role: "viewer", joinedAt: "10:02", talkTimeSec: 65, chatMsgs: 12, pollsAnswered: 3, attentivenessPct: 88, handRaiseCount: 2, cameraOnPct: 78 },
      { id: "a3", name: "Vivek M.", email: "vivek@example.com", role: "viewer", joinedAt: "10:01", talkTimeSec: 22, chatMsgs: 8, pollsAnswered: 3, attentivenessPct: 76, handRaiseCount: 1, cameraOnPct: 40 },
      { id: "a4", name: "Priya N.", email: "priya@example.com", role: "viewer", joinedAt: "10:03", talkTimeSec: 0, chatMsgs: 21, pollsAnswered: 3, attentivenessPct: 92, handRaiseCount: 4, cameraOnPct: 88 },
      { id: "a5", name: "Sandeep R.", email: "sandeep@example.com", role: "viewer", joinedAt: "10:05", talkTimeSec: 11, chatMsgs: 2, pollsAnswered: 1, attentivenessPct: 54, handRaiseCount: 0, cameraOnPct: 12 },
    ],
    recordings: [],
    bbb: seedBBB("m-1", true),
    analytics: {
      engagementScore: 82,
      attendanceRate: 86,
      peakAttendees: 38,
      avgTalkTimeSec: 384,
      chatMsgCount: 47,
      pollsCount: 3,
      handRaisesCount: 7,
      recordingViews: 0,
      avgAttentivenessPct: 82,
      timeline: genTimeline(45, 28, 38),
      polls: [
        { id: "p1", question: "Which collection is thread-safe by default?", options: ["ArrayList", "Vector", "HashMap", "LinkedList"], responseCount: 36, correctIdx: 1, correctPct: 64, askedAtSec: 600 },
        { id: "p2", question: "Time complexity of HashMap get()?", options: ["O(1) avg", "O(log n)", "O(n)", "O(n log n)"], responseCount: 38, correctIdx: 0, correctPct: 79, askedAtSec: 1500 },
        { id: "p3", question: "Pick the immutable collection", options: ["LinkedList", "TreeSet", "List.of()", "ArrayDeque"], responseCount: 35, correctIdx: 2, correctPct: 71, askedAtSec: 2400 },
      ],
    },
  },
  {
    id: "m-2",
    title: "Python Fundamentals — Pandas Workshop",
    description: "Live coding on data wrangling with Pandas.",
    batchId: "11", batchName: "Python Fundamentals — Cohort 14",
    trainerId: "t-2", trainerName: "Priya Nair",
    scheduledAt: offset(1, 0),
    durationMins: 120,
    status: "scheduled",
    joinUrl: "#bbb-join-pending",
    record: true, muteOnJoin: true, waitingRoom: true,
    maxAttendees: 40,
    invitedCount: 38,
    attendees: [],
    recordings: [],
    bbb: seedBBB("m-2", true),
  },
  {
    id: "m-3",
    title: "AWS Solutions Architect — Office Hours",
    batchId: "1", batchName: "AWS Solutions Architect - Batch 12",
    trainerId: "t-3", trainerName: "John Smith",
    scheduledAt: offset(2, 4),
    durationMins: 60,
    status: "scheduled",
    joinUrl: "#bbb-join-pending",
    record: false, muteOnJoin: false, waitingRoom: false,
    maxAttendees: 30,
    invitedCount: 25,
    attendees: [],
    recordings: [],
    bbb: seedBBB("m-3", false),
  },
  {
    id: "m-4",
    title: "Java Fundamentals — Day 12 Recording",
    batchId: "10", batchName: "Java Fundamentals — Cohort 24",
    trainerId: "t-1", trainerName: "Rahul Verma",
    scheduledAt: offset(-2),
    durationMins: 90,
    status: "ended",
    joinUrl: "#bbb-join-pending",
    record: true, muteOnJoin: true, waitingRoom: false,
    maxAttendees: 50,
    invitedCount: 42,
    attendees: [],
    recordings: [
      { id: "r1", title: "Full session", url: "#", durationMins: 88, recordedAt: offset(-2), sizeMb: 420, views: 27 },
    ],
    bbb: seedBBB("m-4", true),
    analytics: {
      engagementScore: 78, attendanceRate: 90, peakAttendees: 40, avgTalkTimeSec: 220, chatMsgCount: 64, pollsCount: 4, handRaisesCount: 11, recordingViews: 27, avgAttentivenessPct: 79,
      timeline: genTimeline(88, 30, 40), polls: [],
    },
  },
  {
    id: "m-5",
    title: "Kubernetes Fundamentals — Networking Deep Dive",
    batchId: "2", batchName: "Kubernetes Fundamentals - Batch 8",
    trainerId: "t-4", trainerName: "Jane Doe",
    scheduledAt: offset(-5),
    durationMins: 75,
    status: "ended",
    joinUrl: "#bbb-join-pending",
    record: true, muteOnJoin: true, waitingRoom: false,
    maxAttendees: 35,
    invitedCount: 30,
    attendees: [],
    recordings: [
      { id: "r2", title: "Full session", url: "#", durationMins: 74, recordedAt: offset(-5), sizeMb: 340, views: 18 },
    ],
    bbb: seedBBB("m-5", true),
    analytics: {
      engagementScore: 71, attendanceRate: 80, peakAttendees: 24, avgTalkTimeSec: 165, chatMsgCount: 52, pollsCount: 2, handRaisesCount: 6, recordingViews: 18, avgAttentivenessPct: 74,
      timeline: genTimeline(74, 18, 24), polls: [],
    },
  },
];

interface MeetingStore {
  meetings: Meeting[];
  addMeeting: (m: Omit<Meeting, "id" | "status" | "joinUrl" | "attendees" | "recordings" | "bbb">) => string;
  updateMeeting: (id: string, updates: Partial<Meeting>) => void;
  deleteMeeting: (id: string) => void;
  getMeeting: (id: string) => Meeting | undefined;
  getMeetingsByBatch: (batchId: string) => Meeting[];
}

export const useMeetingStore = create<MeetingStore>((set, get) => ({
  meetings: initial,
  addMeeting: (m) => {
    const id = `m-${Date.now()}`;
    const meeting: Meeting = {
      ...m,
      id,
      status: new Date(m.scheduledAt) > new Date() ? "scheduled" : "ended",
      joinUrl: "#bbb-join-pending",
      moderatorJoinUrl: "#bbb-mod-pending",
      attendees: [],
      recordings: [],
      bbb: seedBBB(id, m.record),
    };
    set((s) => ({ meetings: [meeting, ...s.meetings] }));
    return id;
  },
  updateMeeting: (id, updates) =>
    set((s) => ({ meetings: s.meetings.map((m) => (m.id === id ? { ...m, ...updates } : m)) })),
  deleteMeeting: (id) =>
    set((s) => ({ meetings: s.meetings.filter((m) => m.id !== id) })),
  getMeeting: (id) => get().meetings.find((m) => m.id === id),
  getMeetingsByBatch: (batchId) => get().meetings.filter((m) => m.batchId === batchId),
}));
